name: Release Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS native (M1/M2/M3)
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: rbxbuild

          # Docker on M1 (ARM Linux)
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact_name: rbxbuild

          # Docker on x86 servers
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: rbxbuild

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        shell: bash
        run: |
          VERSION=$(grep '^version = ' Cargo.toml | cut -d '"' -f2)
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Build with actions-rust-cross
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          command: build
          args: --release
          strip: true   # optional: strips symbols, smaller binary
          use-cross: true

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p release-assets
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} release-assets/rbxbuild-${{ matrix.target }}

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            Automated release for version ${{ steps.version.outputs.version }}

            ## Binaries
            - macOS (M1/M2/M3): `rbxbuild-aarch64-apple-darwin`
            - Linux ARM64 (for Apple Silicon Docker): `rbxbuild-aarch64-unknown-linux-musl`
            - Linux x86_64 (for servers): `rbxbuild-x86_64-unknown-linux-musl`

            Built from commit ${{ github.sha }}
          files: release-assets/*
